# Generated by Django 3.0 on 2020-07-18 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Linkman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15, verbose_name='姓名')),
                ('sex', models.IntegerField(choices=[(1, '男'), (2, '女')], default=1, verbose_name='性別')),
                ('tel', models.CharField(max_length=15, verbose_name='電話')),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='電子郵件')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立日')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日')),
            ],
        ),
    ]
